In [2]:
import torch
torch.__version__

'2.10.0+cu128'

# **1. Scalar Values**

In [3]:
scalar = torch.tensor(8)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

8

# **2. Vector Values**

In [6]:
vector = torch.tensor([1,2,3])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([3])

# **3. Matrix**

In [9]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 3])

# **4. Random Tensors**

In [12]:
random_tensor = torch.rand(size=(2,3))

In [13]:
random_tensor

tensor([[0.3021, 0.1659, 0.1992],
        [0.6045, 0.4329, 0.6359]])

In [14]:
big_tensor = torch.rand(3,4,5)
big_tensor

tensor([[[0.2546, 0.2044, 0.8429, 0.2668, 0.3840],
         [0.8522, 0.0358, 0.0762, 0.2239, 0.3752],
         [0.3187, 0.7842, 0.2670, 0.7040, 0.7947],
         [0.8991, 0.8126, 0.8839, 0.4863, 0.3641]],

        [[0.7781, 0.5996, 0.2405, 0.0276, 0.1710],
         [0.7440, 0.8395, 0.6320, 0.7302, 0.5706],
         [0.3483, 0.9902, 0.0615, 0.7482, 0.0622],
         [0.8510, 0.9011, 0.4153, 0.2340, 0.4290]],

        [[0.5862, 0.1143, 0.8234, 0.3783, 0.4213],
         [0.6685, 0.3064, 0.3824, 0.2904, 0.4269],
         [0.3047, 0.5266, 0.6723, 0.9891, 0.4518],
         [0.3107, 0.0544, 0.0319, 0.0896, 0.0811]]])

# **5. Tensor of Zeros & Ones**

In [15]:
zeros_tensor = torch.zeros(2,3,4)
zeros_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
ones_tensor = torch.ones(2,3,4)
ones_tensor

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

# **6. Creating a range and tensors_like**

**Range**

In [17]:
tensor_with_range = torch.arange(1,10)
tensor_with_range

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
tensor_with_range1 = torch.arange(1,10,2)
tensor_with_range1

tensor([1, 3, 5, 7, 9])

**Tensors like**

In [19]:
sample = torch.rand(3,4)
sample

tensor([[0.2727, 0.1531, 0.1642, 0.4215],
        [0.4164, 0.9215, 0.4159, 0.9550],
        [0.2962, 0.5554, 0.5080, 0.3400]])

In [20]:
zero_like_tensor = torch.zeros_like(sample)
zero_like_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones_like_tensor = torch.ones_like(sample)
ones_like_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

**Torch eye**

In [22]:
# one digonal value
eye_tensor = torch.eye(2)
eye_tensor

tensor([[1., 0.],
        [0., 1.]])

**Torch Full**

In [23]:
full_tensor = torch.full((2,3),1)
full_tensor1 = torch.full((2,3),2)
print(full_tensor)
print(full_tensor1)

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[2, 2, 2],
        [2, 2, 2]])


**Torch linspace**

In [24]:
linear_tensor = torch.linspace(1,10,5)
linear_tensor

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

# **7. Tensor Datatypes**

In [25]:
simple = torch.arange(2,5,dtype=int)
simple.dtype

torch.int64

In [26]:
x = simple.type(torch.float16)
x.dtype

torch.float16

# **8. Getting Information from Tensors**

shape:dtype:device:

In [27]:
some_tensor = torch.rand(3,4)
some_tensor.shape

torch.Size([3, 4])

In [28]:
some_tensor.dtype

torch.float32

In [29]:
some_tensor.device

device(type='cpu')

# **9. Manupulating Tensors ( Tensor Opretions )**
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Devision
5. Matrix Multiplicaiton

**1. Addition**

In [30]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [31]:
tensor + 10

tensor([11, 12, 13])

In [32]:
tensor_a = torch.tensor([3,4,5])
tensor_b = torch.tensor([5,6,7])
tensor_a + tensor_b

tensor([ 8, 10, 12])

In [33]:
torch.add(tensor_a,tensor_b)

tensor([ 8, 10, 12])

**2. Substraction**

In [34]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [35]:
tensor - 13

tensor([-12, -11, -10])

In [36]:
# both work similarly
torch.subtract(tensor,13)
torch.sub(tensor,13)

tensor([-12, -11, -10])

**3. Multiplication (element-wise)**

In [37]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [38]:
tensor * 10

tensor([10, 20, 30])

In [39]:
torch.multiply(tensor,10)
torch.mul(tensor,tensor)

tensor([1, 4, 9])

**4. Division**

In [40]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [41]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

**5. Matrix Multiplication**

In [42]:
matrix_a = torch.tensor([[1,2],[3,4]])
matrix_b = torch.tensor([[5,6],[7,8]])
matrix_a,matrix_b

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [43]:
matrix_a.shape, matrix_b.shape

(torch.Size([2, 2]), torch.Size([2, 2]))

In [44]:
# normal multiplication
matrix_a * matrix_b

tensor([[ 5, 12],
        [21, 32]])

In [45]:
# matrix multiplication
matrix_a @ matrix_b

tensor([[19, 22],
        [43, 50]])

In [46]:
torch.mm(matrix_a,matrix_b)

tensor([[19, 22],
        [43, 50]])

In [47]:
torch.matmul(matrix_a,matrix_b)

tensor([[19, 22],
        [43, 50]])

**6. One of the most common error in deep learning (shape error)**

In [48]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]],dtype=torch.float32)
tensor_B = torch.tensor([[7,8],[9,10],[11,12]],dtype=torch.float32)
tensor_A,tensor_B

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]))

In [49]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [50]:
tensor_A.T.shape, tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [51]:
torch.matmul(tensor_A.T,tensor_B)

tensor([[ 89.,  98.],
        [116., 128.]])

**7. Find mean,sum , max, min**

In [52]:
tensor = torch.arange(1.,10.)

In [53]:
tensor.min()

tensor(1.)

In [54]:
tensor.max()

tensor(9.)

In [55]:
tensor.sum()

tensor(45.)

In [56]:
# it will not work on the int data bcz in Ai we mostly use float values
tensor.mean()

tensor(5.)

Positional max and min

In [57]:
sample = torch.arange(1,10)
sample

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
sample.min()

tensor(1)

In [59]:
sample.argmin()

tensor(0)

In [60]:
sample.max()

tensor(9)

In [61]:
sample.argmax()

tensor(8)

# **10. Reshaping , Stacking , Squeezing , Unsqeeze , Permute**

**Reshape**

In [62]:
x = torch.arange(1.,9.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [63]:
x_reshaped = x.reshape(2,2,2)
x_reshaped

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

**View (It also change the main tensor rather then the copy of the tensor)**

In [64]:
y = torch.arange(1.,9.)
y

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [65]:
y_view = y.view(2,4)
y_view

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

**Torch.stack()**

In [66]:
tensor_stacked = torch.stack([tensor,tensor,tensor, tensor],dim=0)
tensor_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [67]:
tensor_stacked = torch.stack([tensor,tensor,tensor, tensor],dim=1)
tensor_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

**Torch.unsqueeze()**

In [68]:
x = torch.arange(1.,8.)
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [69]:
x.shape,x.ndim

(torch.Size([7]), 1)

In [70]:
x_unsqueezed = x.unsqueeze(dim=0)
x_unsqueezed.shape,x_unsqueezed.ndim

(torch.Size([1, 7]), 2)

**Torch.squeeze()**

In [71]:
x_squeeze = x_unsqueezed.squeeze()
x_squeeze.shape,x_squeeze.ndim

(torch.Size([7]), 1)

**Permute**

In [72]:
x = torch.rand(2,3,5,5,6,4,8)
x

tensor([[[[[[[7.1085e-01, 4.8301e-01, 5.1566e-01,  ..., 3.9847e-01,
              1.3224e-01, 6.9033e-01],
             [2.0686e-02, 2.1328e-01, 4.8307e-01,  ..., 3.7225e-02,
              5.3269e-01, 2.7704e-01],
             [6.5097e-01, 8.0178e-01, 3.8683e-01,  ..., 9.5240e-01,
              2.9635e-01, 8.3849e-02],
             [4.3585e-01, 8.3069e-01, 6.9738e-02,  ..., 4.1608e-01,
              4.0760e-02, 1.1147e-01]],

            [[1.2575e-01, 9.5543e-01, 2.0591e-01,  ..., 3.4636e-01,
              4.2723e-01, 5.9642e-01],
             [2.0663e-01, 5.8836e-01, 2.6907e-01,  ..., 5.2005e-01,
              1.3496e-01, 6.3401e-01],
             [5.2443e-01, 5.3528e-01, 9.7637e-01,  ..., 6.1960e-01,
              9.2388e-01, 9.7244e-01],
             [8.4397e-02, 8.9116e-01, 7.5042e-01,  ..., 8.2962e-01,
              9.6166e-01, 9.8951e-01]],

            [[1.2008e-01, 3.9053e-01, 4.5735e-01,  ..., 9.1974e-01,
              1.5359e-01, 4.7648e-01],
             [4.7389e-01, 4.4047e

In [73]:
x.shape

torch.Size([2, 3, 5, 5, 6, 4, 8])

In [74]:
# also change the original tensor
x_permute = x.permute(6,5,4,3,2,1,0)
x_permute.shape

torch.Size([8, 4, 6, 5, 5, 3, 2])

# **11. Indexing (selecting data form the tensors)**

In [75]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [76]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [77]:
x[0,0]

tensor([1, 2, 3])

In [78]:
x[0,1]

tensor([4, 5, 6])

In [79]:
x[0,1,1]

tensor(5)

# **12. Pytorch Tensors and Numpy**

In [80]:
import numpy as np

In [81]:
array = np.arange(1.0,8.0)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [82]:
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [83]:
numpy_array = tensor.numpy()
numpy_array

array([1., 2., 3., 4., 5., 6., 7.])

# **13. Reproducibility**

In [84]:
random_tensor_A = torch.rand(3,4)
random_tensor_A

tensor([[0.4706, 0.5642, 0.4922, 0.1789],
        [0.9920, 0.4468, 0.5351, 0.4170],
        [0.7006, 0.2017, 0.5214, 0.8357]])

In [85]:
random_tensor_B = torch.rand(3,4)
random_tensor_B

tensor([[0.2997, 0.6279, 0.1019, 0.7957],
        [0.8271, 0.0054, 0.3608, 0.2691],
        [0.2388, 0.0814, 0.7708, 0.7084]])

In [86]:
random_seed = 42
torch.manual_seed(random_seed)
random_tensor_C = torch.rand(3,4)
random_tensor_C

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [87]:
torch.manual_seed(random_seed)
random_tensor_D = torch.rand(3,4)
random_tensor_D

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

# **14. Running Tensors on GPU**

In [88]:
torch.cuda.is_available()

True

In [90]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [92]:
torch.cuda.device_count()

1

In [93]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [94]:
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [96]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [99]:
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu.device

device(type='cpu')