In [6]:
import torch
torch.__version__

'2.10.0+cpu'

# **1. Scalar Values**

In [7]:
scalar = torch.tensor(8)

In [11]:
scalar.ndim

0

In [12]:
scalar.item()

8

# **2. Vector Values**

In [13]:
vector = torch.tensor([1,2,3])

In [14]:
vector.ndim

1

In [16]:
vector.shape

torch.Size([3])

# **3. Matrix**

In [18]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
matrix.ndim

2

In [20]:
matrix.shape

torch.Size([2, 3])

# **4. Random Tensors**

In [21]:
random_tensor = torch.rand(size=(2,3))

In [22]:
random_tensor

tensor([[0.9100, 0.8793, 0.9603],
        [0.9921, 0.3277, 0.7811]])

In [24]:
big_tensor = torch.rand(3,4,5)
big_tensor

tensor([[[0.0361, 0.1257, 0.0582, 0.3627, 0.2763],
         [0.3361, 0.4769, 0.2164, 0.9039, 0.0440],
         [0.7820, 0.1600, 0.4166, 0.7987, 0.7262],
         [0.9778, 0.5520, 0.5509, 0.9098, 0.9136]],

        [[0.2888, 0.9071, 0.0432, 0.9351, 0.3710],
         [0.2976, 0.5201, 0.4178, 0.6204, 0.5040],
         [0.6271, 0.1204, 0.4720, 0.9757, 0.9821],
         [0.4371, 0.1610, 0.0054, 0.9941, 0.2967]],

        [[0.7024, 0.2271, 0.9400, 0.4527, 0.8966],
         [0.6788, 0.1017, 0.8010, 0.4294, 0.8424],
         [0.5092, 0.5858, 0.4217, 0.8922, 0.4167],
         [0.2174, 0.7467, 0.4699, 0.0994, 0.2899]]])

# **5. Tensor of Zeros & Ones**

In [26]:
zeros_tensor = torch.zeros(2,3,4)
zeros_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [28]:
ones_tensor = torch.ones(2,3,4)
ones_tensor

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

# **6. Creating a range and tensors_like**

**Range**

In [29]:
tensor_with_range = torch.arange(1,10)
tensor_with_range

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
tensor_with_range1 = torch.arange(1,10,2)
tensor_with_range1

tensor([1, 3, 5, 7, 9])

**Tensors like**

In [33]:
sample = torch.rand(3,4)
sample

tensor([[0.6630, 0.4287, 0.9556, 0.0569],
        [0.8036, 0.0075, 0.8358, 0.2665],
        [0.9182, 0.4319, 0.3154, 0.5687]])

In [35]:
zero_like_tensor = torch.zeros_like(sample)
zero_like_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
ones_like_tensor = torch.ones_like(sample)
ones_like_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

**Torch eye**

In [39]:
# one digonal value
eye_tensor = torch.eye(2)
eye_tensor

tensor([[1., 0.],
        [0., 1.]])

**Torch Full**

In [46]:
full_tensor = torch.full((2,3),1)
full_tensor1 = torch.full((2,3),2)
print(full_tensor)
print(full_tensor1)

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[2, 2, 2],
        [2, 2, 2]])
