In [2]:
import torch
torch.__version__

'2.10.0+cpu'

# **1. Scalar Values**

In [3]:
scalar = torch.tensor(8)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

8

# **2. Vector Values**

In [6]:
vector = torch.tensor([1,2,3])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([3])

# **3. Matrix**

In [9]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 3])

# **4. Random Tensors**

In [12]:
random_tensor = torch.rand(size=(2,3))

In [13]:
random_tensor

tensor([[0.5439, 0.2411, 0.2517],
        [0.1839, 0.5125, 0.0536]])

In [14]:
big_tensor = torch.rand(3,4,5)
big_tensor

tensor([[[0.1616, 0.9819, 0.9517, 0.0214, 0.4951],
         [0.8259, 0.1928, 0.5285, 0.2600, 0.3009],
         [0.5624, 0.4406, 0.7419, 0.8925, 0.4101],
         [0.3779, 0.8555, 0.5898, 0.4520, 0.2712]],

        [[0.6721, 0.8884, 0.8969, 0.0753, 0.6355],
         [0.9487, 0.1554, 0.4562, 0.6114, 0.2705],
         [0.3433, 0.6777, 0.2241, 0.1096, 0.9926],
         [0.1164, 0.4563, 0.6358, 0.6783, 0.9901]],

        [[0.6385, 0.4513, 0.1071, 0.9054, 0.6599],
         [0.8743, 0.0595, 0.8831, 0.7786, 0.9445],
         [0.8608, 0.8934, 0.7917, 0.3172, 0.4014],
         [0.2214, 0.7965, 0.9987, 0.6594, 0.9672]]])

# **5. Tensor of Zeros & Ones**

In [15]:
zeros_tensor = torch.zeros(2,3,4)
zeros_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
ones_tensor = torch.ones(2,3,4)
ones_tensor

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

# **6. Creating a range and tensors_like**

**Range**

In [17]:
tensor_with_range = torch.arange(1,10)
tensor_with_range

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
tensor_with_range1 = torch.arange(1,10,2)
tensor_with_range1

tensor([1, 3, 5, 7, 9])

**Tensors like**

In [19]:
sample = torch.rand(3,4)
sample

tensor([[0.1608, 0.3995, 0.9890, 0.8341],
        [0.6693, 0.5027, 0.6794, 0.6922],
        [0.4074, 0.8682, 0.3564, 0.4726]])

In [20]:
zero_like_tensor = torch.zeros_like(sample)
zero_like_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones_like_tensor = torch.ones_like(sample)
ones_like_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

**Torch eye**

In [22]:
# one digonal value
eye_tensor = torch.eye(2)
eye_tensor

tensor([[1., 0.],
        [0., 1.]])

**Torch Full**

In [23]:
full_tensor = torch.full((2,3),1)
full_tensor1 = torch.full((2,3),2)
print(full_tensor)
print(full_tensor1)

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[2, 2, 2],
        [2, 2, 2]])


**Torch linspace**

In [25]:
linear_tensor = torch.linspace(1,10,5)
linear_tensor

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

# **7. Tensor Datatypes**

In [27]:
simple = torch.arange(2,5,dtype=int)
simple.dtype

torch.int64

In [32]:
x = simple.type(torch.float16)
x.dtype

torch.float16

# **8. Getting Information from Tensors**

shape:dtype:device:

In [33]:
some_tensor = torch.rand(3,4)
some_tensor.shape

torch.Size([3, 4])

In [34]:
some_tensor.dtype

torch.float32

In [35]:
some_tensor.device

device(type='cpu')

# **9. Manupulating Tensors ( Tensor Opretions )**
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Devision
5. Matrix Multiplicaiton

1. Addition

In [37]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [38]:
tensor + 10

tensor([11, 12, 13])

In [39]:
tensor_a = torch.tensor([3,4,5])
tensor_b = torch.tensor([5,6,7])
tensor_a + tensor_b

tensor([ 8, 10, 12])

In [40]:
torch.add(tensor_a,tensor_b)

tensor([ 8, 10, 12])

2. Substraction

In [41]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [42]:
tensor - 13

tensor([-12, -11, -10])

In [45]:
# both work similarly
torch.subtract(tensor,13)
torch.sub(tensor,13)

tensor([-12, -11, -10])

3. Multiplication (element-wise)

In [46]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [47]:
tensor * 10

tensor([10, 20, 30])

In [50]:
torch.multiply(tensor,10)
torch.mul(tensor,tensor)

tensor([1, 4, 9])

4. Division

In [52]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [53]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

5. Matrix Multiplication

In [54]:
matrix_a = torch.tensor([[1,2],[3,4]])
matrix_b = torch.tensor([[5,6],[7,8]])
matrix_a,matrix_b

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [55]:
matrix_a.shape, matrix_b.shape

(torch.Size([2, 2]), torch.Size([2, 2]))

In [56]:
# normal multiplication
matrix_a * matrix_b

tensor([[ 5, 12],
        [21, 32]])

In [57]:
# matrix multiplication
matrix_a @ matrix_b

tensor([[19, 22],
        [43, 50]])

In [59]:
torch.mm(matrix_a,matrix_b)

tensor([[19, 22],
        [43, 50]])

In [60]:
torch.matmul(matrix_a,matrix_b)

tensor([[19, 22],
        [43, 50]])

6. One of the most common error in deep learning (shape error)

In [61]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]],dtype=torch.float32)
tensor_B = torch.tensor([[7,8],[9,10],[11,12]],dtype=torch.float32)
tensor_A,tensor_B

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]))

In [62]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [65]:
tensor_A.T.shape, tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [64]:
torch.matmul(tensor_A.T,tensor_B)

tensor([[ 89.,  98.],
        [116., 128.]])