In [1]:
import torch
torch.__version__

'2.10.0+cpu'

# **1. Scalar Values**

In [2]:
scalar = torch.tensor(8)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

8

# **2. Vector Values**

In [5]:
vector = torch.tensor([1,2,3])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([3])

# **3. Matrix**

In [8]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 3])

# **4. Random Tensors**

In [11]:
random_tensor = torch.rand(size=(2,3))

In [12]:
random_tensor

tensor([[0.2259, 0.1090, 0.0105],
        [0.9846, 0.5760, 0.7193]])

In [13]:
big_tensor = torch.rand(3,4,5)
big_tensor

tensor([[[0.4187, 0.9599, 0.8111, 0.6641, 0.6650],
         [0.8663, 0.0257, 0.2891, 0.6490, 0.6868],
         [0.4988, 0.2284, 0.0172, 0.2348, 0.1446],
         [0.1230, 0.5474, 0.2566, 0.4814, 0.1167]],

        [[0.2814, 0.0511, 0.2653, 0.6829, 0.2462],
         [0.7895, 0.1934, 0.8980, 0.6971, 0.7944],
         [0.8633, 0.0840, 0.0666, 0.3870, 0.1159],
         [0.5160, 0.1977, 0.5775, 0.9120, 0.0682]],

        [[0.0518, 0.2274, 0.3294, 0.7756, 0.0551],
         [0.4077, 0.9026, 0.2550, 0.5771, 0.1694],
         [0.1709, 0.6995, 0.4306, 0.8048, 0.6018],
         [0.2939, 0.0012, 0.8649, 0.9169, 0.6427]]])

# **5. Tensor of Zeros & Ones**

In [14]:
zeros_tensor = torch.zeros(2,3,4)
zeros_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
ones_tensor = torch.ones(2,3,4)
ones_tensor

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

# **6. Creating a range and tensors_like**

**Range**

In [16]:
tensor_with_range = torch.arange(1,10)
tensor_with_range

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
tensor_with_range1 = torch.arange(1,10,2)
tensor_with_range1

tensor([1, 3, 5, 7, 9])

**Tensors like**

In [18]:
sample = torch.rand(3,4)
sample

tensor([[0.0236, 0.9659, 0.1232, 0.4446],
        [0.5751, 0.8485, 0.1479, 0.4726],
        [0.5031, 0.2339, 0.7076, 0.5238]])

In [19]:
zero_like_tensor = torch.zeros_like(sample)
zero_like_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones_like_tensor = torch.ones_like(sample)
ones_like_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

**Torch eye**

In [21]:
# one digonal value
eye_tensor = torch.eye(2)
eye_tensor

tensor([[1., 0.],
        [0., 1.]])

**Torch Full**

In [22]:
full_tensor = torch.full((2,3),1)
full_tensor1 = torch.full((2,3),2)
print(full_tensor)
print(full_tensor1)

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[2, 2, 2],
        [2, 2, 2]])


**Torch linspace**

In [23]:
linear_tensor = torch.linspace(1,10,5)
linear_tensor

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

# **7. Tensor Datatypes**

In [24]:
simple = torch.arange(2,5,dtype=int)
simple.dtype

torch.int64

In [25]:
x = simple.type(torch.float16)
x.dtype

torch.float16

# **8. Getting Information from Tensors**

shape:dtype:device:

In [26]:
some_tensor = torch.rand(3,4)
some_tensor.shape

torch.Size([3, 4])

In [27]:
some_tensor.dtype

torch.float32

In [28]:
some_tensor.device

device(type='cpu')

# **9. Manupulating Tensors ( Tensor Opretions )**
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Devision
5. Matrix Multiplicaiton

**1. Addition**

In [29]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [30]:
tensor + 10

tensor([11, 12, 13])

In [31]:
tensor_a = torch.tensor([3,4,5])
tensor_b = torch.tensor([5,6,7])
tensor_a + tensor_b

tensor([ 8, 10, 12])

In [32]:
torch.add(tensor_a,tensor_b)

tensor([ 8, 10, 12])

**2. Substraction**

In [33]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [34]:
tensor - 13

tensor([-12, -11, -10])

In [35]:
# both work similarly
torch.subtract(tensor,13)
torch.sub(tensor,13)

tensor([-12, -11, -10])

**3. Multiplication (element-wise)**

In [36]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [37]:
tensor * 10

tensor([10, 20, 30])

In [38]:
torch.multiply(tensor,10)
torch.mul(tensor,tensor)

tensor([1, 4, 9])

**4. Division**

In [39]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [40]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

**5. Matrix Multiplication**

In [41]:
matrix_a = torch.tensor([[1,2],[3,4]])
matrix_b = torch.tensor([[5,6],[7,8]])
matrix_a,matrix_b

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [42]:
matrix_a.shape, matrix_b.shape

(torch.Size([2, 2]), torch.Size([2, 2]))

In [43]:
# normal multiplication
matrix_a * matrix_b

tensor([[ 5, 12],
        [21, 32]])

In [44]:
# matrix multiplication
matrix_a @ matrix_b

tensor([[19, 22],
        [43, 50]])

In [45]:
torch.mm(matrix_a,matrix_b)

tensor([[19, 22],
        [43, 50]])

In [46]:
torch.matmul(matrix_a,matrix_b)

tensor([[19, 22],
        [43, 50]])

**6. One of the most common error in deep learning (shape error)**

In [47]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]],dtype=torch.float32)
tensor_B = torch.tensor([[7,8],[9,10],[11,12]],dtype=torch.float32)
tensor_A,tensor_B

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]))

In [48]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [49]:
tensor_A.T.shape, tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [50]:
torch.matmul(tensor_A.T,tensor_B)

tensor([[ 89.,  98.],
        [116., 128.]])

**7. Find mean,sum , max, min**

In [57]:
tensor = torch.arange(1.,10.)

In [58]:
tensor.min()

tensor(1.)

In [59]:
tensor.max()

tensor(9.)

In [60]:
tensor.sum()

tensor(45.)

In [62]:
# it will not work on the int data bcz in Ai we mostly use float values
tensor.mean()

tensor(5.)

Positional max and min

In [64]:
sample = torch.arange(1,10)
sample

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
sample.min()

tensor(1)

In [65]:
sample.argmin()

tensor(0)

In [67]:
sample.max()

tensor(9)

In [68]:
sample.argmax()

tensor(8)

# **10. Reshaping , Stacking , Squeezing , Unsqeeze , Permute**

**Reshape**

In [69]:
x = torch.arange(1.,9.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [71]:
x_reshaped = x.reshape(2,2,2)
x_reshaped

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

**View (It also change the main tensor rather then the copy of the tensor)**

In [73]:
y = torch.arange(1.,9.)
y

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [74]:
y_view = y.view(2,4)
y_view

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

**Torch.stack()**

In [78]:
tensor_stacked = torch.stack([tensor,tensor,tensor, tensor],dim=0)
tensor_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [79]:
tensor_stacked = torch.stack([tensor,tensor,tensor, tensor],dim=1)
tensor_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

**Torch.unsqueeze()**

In [81]:
x = torch.arange(1.,8.)
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [83]:
x.shape,x.ndim

(torch.Size([7]), 1)

In [85]:
x_unsqueezed = x.unsqueeze(dim=0)
x_unsqueezed.shape,x_unsqueezed.ndim

(torch.Size([1, 7]), 2)

**Torch.squeeze()**

In [86]:
x_squeeze = x_unsqueezed.squeeze()
x_squeeze.shape,x_squeeze.ndim

(torch.Size([7]), 1)

**Permute**

In [91]:
x = torch.rand(2,3,5,5,6,4,8)
x

tensor([[[[[[[3.9032e-01, 2.7341e-01, 5.1249e-02,  ..., 9.9500e-01,
              7.0054e-01, 2.9754e-02],
             [4.3878e-01, 9.7868e-01, 6.7728e-01,  ..., 5.1831e-01,
              3.2712e-01, 9.4821e-01],
             [1.0520e-01, 8.7973e-01, 5.7839e-01,  ..., 8.3514e-01,
              5.6315e-01, 3.9153e-02],
             [5.5764e-01, 5.8654e-01, 8.8747e-01,  ..., 8.0502e-02,
              9.6902e-01, 1.2868e-01]],

            [[6.8468e-01, 2.0948e-01, 3.3018e-01,  ..., 4.3341e-01,
              5.7903e-01, 9.0329e-01],
             [5.0044e-03, 9.1909e-01, 8.0896e-01,  ..., 5.8798e-01,
              8.1142e-01, 7.1273e-02],
             [7.6040e-01, 8.5665e-01, 2.4560e-01,  ..., 6.6565e-01,
              6.8031e-01, 6.4245e-01],
             [4.6919e-01, 6.2658e-01, 2.1150e-01,  ..., 9.3261e-01,
              1.4389e-01, 1.7548e-01]],

            [[4.4701e-01, 7.5996e-01, 9.6484e-01,  ..., 9.4817e-01,
              2.5953e-01, 1.9707e-01],
             [9.8756e-01, 4.9124e

In [92]:
x.shape

torch.Size([2, 3, 5, 5, 6, 4, 8])

In [95]:
# also change the original tensor
x_permute = x.permute(6,5,4,3,2,1,0)
x_permute.shape

torch.Size([8, 4, 6, 5, 5, 3, 2])

# **11. Indexing (selecting data form the tensors)**

In [97]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [98]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [100]:
x[0,0]

tensor([1, 2, 3])

In [101]:
x[0,1]

tensor([4, 5, 6])

In [102]:
x[0,1,1]

tensor(5)